name: Build & Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Сборка CFE
    uses: ShadobaAI/kafka-tools/.github/workflows/release-1c-artifacts.yml@main
